import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigator from "./_Component/navigation";
import { Theme } from "@radix-ui/themes";
import DarkThemeSwitch from "./_Component/darkthemeswitch";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-hidden bg-white h-screen dark:bg-black">
        <Theme>
          <div className="flex flex-col h-screen">
            <div className="flex flex-col">
              <DarkThemeSwitch />
            </div>
            <div className="flex-grow flex max-w-full overflow-y-auto">
              {children}
            </div>
            <div>
              <Navigator />
            </div>
          </div>
        </Theme>
      </body>
    </html>
  );
}
